import type { Metadata } from "next";
import { Catamaran, Crimson_Text } from "next/font/google";
import "./globals.css";
import MobileMenu from "./components/organism/MobileMenu";
import MobileHeader from "./components/organism/MobileHeader";
import DesktopHeader from "./components/organism/DesktopHeader";

const crimsonText = Crimson_Text({
      variable: "--font-crimson-text",
      weight: ["400", "600", "700"],
      subsets: ["latin"],
});

const catamaran = Catamaran({
      variable: "--font-catamaran",
      weight: ["300", "400", "500"],
      subsets: ["latin"],
});

export const metadata: Metadata = {
      title: "Create Next App",
      description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
      return (
            <html
                  lang="en"
                  className={` ${crimsonText.variable} ${catamaran.variable} h-full antialiased`}
            >

                  <body className="min-h-full flex flex-col text-text">
                        <header>
                              <MobileHeader />
                              <DesktopHeader />
                        </header>
                        <MobileMenu />
                        <main>{children}</main>
                        <footer></footer>
                  </body>
            </html>
      );
}
